CREATE DATABASE MERCADO;

USE MERCADO;

CREATE TABLE CLIENTE(
	CPF VARCHAR(15) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SOBRENOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL UNIQUE,
	SEXO ENUM('M', 'F') NOT NULL,
	NASCIMENTO DATE NOT NULL
);


CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	NUMERO VARCHAR(5) NOT NULL,
	CEP VARCHAR(12) NOT NULL,
	CPF_CLIENTE VARCHAR(15)
);


CREATE TABLE VENDA(
	IDVENDA INT PRIMARY KEY AUTO_INCREMENT,
	VALOR_TOTAL FLOAT(10,2) NOT NULL,
	DATA DATETIME NOT NULL,
	ECONOMIA_CLIENTE FLOAT(10,2),
	CPF_CLIENTE VARCHAR(15)
);


CREATE TABLE OPCAO(
	IDOPCAO INT PRIMARY KEY AUTO_INCREMENT,
	VALOR_PAGO FLOAT NOT NULL,
	TIPO VARCHAR(30) NOT NULL,
	ID_VENDA INT
);


CREATE TABLE PRODUTO(
	CODIGO INT PRIMARY KEY,
	PRECO_NORMAL FLOAT(10,2) NOT NULL,
	PRECO_CLIENTE FLOAT(10,2),
	DESCRICAO VARCHAR(50) NOT NULL
);



ALTER TABLE OPCAO ADD CONSTRAINT FK_VENDA_OPCAO
FOREIGN KEY (ID_VENDA) REFERENCES VENDA(IDVENDA);

ALTER TABLE ENDERECO 
ADD CONSTRAINT FK_CLIENTE_ENDERECO
FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF);

ALTER TABLE VENDA 
ADD CONSTRAINT FK_CLIENTE_VENDA
FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF);



/*
1 - FAZER UMA TELA DE LOGIN DE CLIENTE
	1.1 - NELA VAI CONTER O CADASTRO DOS ITENS NECESSÁRIOS PARA O CADASTRO DE CLIENTE NO BANCO
	1.2 - CADASTRAR TAMBÉM OS DADOS DE ENDERECO DO CLIENTE
	1.3 - DEPOIS DE CADASTRADO ELA SE ENCERRA.
2 - FAZER A CRIAÇÃO DO SISTEMA PDV INTEGRADO COM O BANCO DE DADOS
	2.1 - FAZER O CADASTRO DOS PRODUTOS NO BANCO
	2.2 - ANTES DE INICIAR A COMPRA, PERGUNTAR SE O CLIENTE TEM O CADASTRO OU NÃO
		2.2.1 - SE O CLIENTE NÃO TEM CADASTRO USAR O PRECO_NORMAL DA TABELA PRODUTO NA HORA DE PASSAR A COMPRA
	2.3 - NA FORMA DE PAGAMENTO, DEPOIS DAS EXCESSOES A ERROS, TODA A FORMA DE PAGAMENTO DEVE SER INSERIDA NO BANCO, JUNTO DO VALOR PAGO
	2.4 - DEPOIS QUE A COMPRA FOR FINALIZADA SERÁ NECESSÁRIO CADASTRAR AS INFORMAÇÕES NECESSARIAS NO BANCO
3 - ENQUANTO O PDV NAO FOR ENCERRADO, UMA NOVA COMPRA VAI RECOMEÇAR E NOVOS DADOS DEVEM SER CADASTRADOS NO BANCO.
*/	


INSERT INTO PRODUTO VALUES('2295', 5.99, 4.99, 'Banana Nanica kg');
INSERT INTO PRODUTO VALUES('2219', 7.99, NULL, 'Banana prata kg');
INSERT INTO PRODUTO VALUES('2172', 9.99, NULL, 'Maçã Fuji kg');
INSERT INTO PRODUTO VALUES('2547', 8.99, NULL, 'Maçã Gala kg');
INSERT INTO PRODUTO VALUES('2127', 12.40, 8.69, 'Mamão Papaya kg');
INSERT INTO PRODUTO VALUES('2134', 10.99, NULL, 'Mamão Formosa kg');
INSERT INTO PRODUTO VALUES('5843', 12.00, NULL, 'Pão Francês kg');
INSERT INTO PRODUTO VALUES('1052', 8.99, 5.99, 'Tomate Carmem kg');
INSERT INTO PRODUTO VALUES('7622210194046', 12.27, 11.99, 'CHOCOLATE MILKA 100G un');
INSERT INTO PRODUTO VALUES('9788575225639', 56.00, NULL, 'Entendendo algoritmos un');
INSERT INTO PRODUTO VALUES('5601229873236', 3.00, NULL, 'Lapiseira Molin 0,7mm un');
INSERT INTO PRODUTO VALUES('7898938236034', 6.69, 4.99, 'Coca-Cola Garrafa Pet 2L un');


CREATE VIEW RELATORIO_CLIENTE AS
	SELECT C.CPF, C.NOME, C.SOBRENOME, E.CIDADE, E.CEP, SUM(V.VALOR_TOTAL) AS TOTAL_GASTO, SUM(V.ECONOMIA_CLIENTE) AS ECONOMIA_TOTAL FROM CLIENTE C
	LEFT JOIN ENDERECO E
	ON C.CPF = E.CPF_CLIENTE
	LEFT JOIN VENDA V
	ON C.CPF = V.CPF_CLIENTE
	GROUP BY 1
	ORDER BY 6 DESC;
	
	
CREATE VIEW RELATORIO_CIDADE AS
	SELECT E.CIDADE, SUM(V.VALOR_TOTAL) AS TOTAL_GASTO FROM ENDERECO E
	LEFT JOIN VENDA V
	ON E.CPF_CLIENTE = V.CPF_CLIENTE
	GROUP BY 1
	ORDER BY 2 DESC;
